import React from "react";
import Markdown from "./Markdown";
import HTTPSnippet from "httpsnippet";
import { parseParams } from "./InsomniaDocs";

export type Props = { resource: InsomniaResource; insomnia: Insomnia };

export function dataFrom(resource: InsomniaResource, insomnia: Insomnia): HTTPSnippet.Data {
	const data = {
		method: resource.method,
		url: parseParams(resource, insomnia).url,
		cookies: insomnia.resources.filter(res => res._type === "cookie_jar")[0].cookies.map(cookie => ({
			name: cookie.name,
		    value: cookie.value
		})),
		headers: resource.headers.map(header => ({
			name: header.name,
			value: header.value
		}))
	} as HTTPSnippet.Data;
	return data;

}

export default function InsomniaSnippet({ resource, insomnia }: Props): JSX.Element {

	const httpSnippetData = dataFrom(resource, insomnia);
	console.log(httpSnippetData);
	const snippet = new HTTPSnippet(httpSnippetData);

	return (
		<>
			<Markdown>{`
\`\`\`js
${snippet.convert("javascript", "fetch")}
\`\`\`

Generated by [Kong/httpsnippet](https://github.com/Kong/httpsnippet)
				`}
			</Markdown>
		</>
	);
}
